const ActionTypes = {
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_RESPONSE: "UPDATE_USER_RESPONSE",
    GET_USERS: "GET_USERS",
    GET_USERS_RESPONSE: "GET_USER_RESPONSE",
    ADD_USER: "ADD_USER",
    ADD_USER_RESPONSE: "ADD_USER_RESPONSE",
    DEL_USER: "DEL_USER",
    DEL_USER_RESPONSE: "DEL_USER_RESPONSE",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    UPDATE_PRODUCT_RESPONSE: "UPDATE_PRODUCT_RESPONSE",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_RESPONSE: "GET_PRODUCTS_RESPONSE",
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_RESPONSE: "ADD_PRODUCT_RESPONSE",
    DEL_PRODUCT: "DEL_PRODUCT",
    DEL_PRODUCT_RESPONSE: "DEL_PRODUCT_RESPONSE"
}

export default ActionTypes;